#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DMSvStandard.Resource", IsApplication=true)]

namespace DMSvStandard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::DMSvStandard.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::DMSvStandard.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::DMSvStandard.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::DMSvStandard.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::DMSvStandard.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::DMSvStandard.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::DMSvStandard.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::DMSvStandard.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::DMSvStandard.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::DMSvStandard.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::DMSvStandard.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::DMSvStandard.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::DMSvStandard.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::DMSvStandard.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::DMSvStandard.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::DMSvStandard.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::DMSvStandard.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::DMSvStandard.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::DMSvStandard.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::DMSvStandard.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::DMSvStandard.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::DMSvStandard.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::DMSvStandard.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::DMSvStandard.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::DMSvStandard.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::DMSvStandard.Resource.Styleable.ProgressWheel_ahTextSize;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::DMSvStandard.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::DMSvStandard.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::DMSvStandard.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int anomalielivraisonlist = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int anomalieramasselist = 2131230721;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int bleudms = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int btnbackred = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int btndef = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int btnfocus = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int btnpressed = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int activity = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Anom = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int anomalie_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Anompj = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arrow75 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backstroke = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bleu_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bleu_buttontwo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bleumenu_button = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int boxgray = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dealtis_fonte = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dealtis_fonte_ol = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int delivery = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Draft = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int DTMD = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int email19 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Enl = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int fkman = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int fkmanbis = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int gray_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int green_listview = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_errorstatus = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_successstatus = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int iconapp = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int imgButtonBgColor = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Inbox = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int jaune_button = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Liv = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int LivAdr = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int Livpadr = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int livraison_button = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int magnifier13 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int man13 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int man13bis = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int MessageListSelector = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int moinshuitmille = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int newmessageicon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int newMsg = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int nonewmessagesicon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int outbox = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int panneauadrlimite = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int peekup = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int plushuitmille = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int receiving5 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int red_button = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int red_listview = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int rounded_text = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int roundedbg = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int roundedbgdark = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int SBBadgeBG = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int SBBadgeBGGREEN = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int SBBadgeBGUP = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int send = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Settings = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int splashscreen = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int splashscreeng = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int transport359 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int transport359b = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int trip = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int Val = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int valide_button = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int violet_button = 2130837567;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090081
			public const int Image = 2131296385;
			
			// aapt resource value: 0x7f09009d
			public const int SujListView = 2131296413;
			
			// aapt resource value: 0x7f090082
			public const int Text = 2131296386;
			
			// aapt resource value: 0x7f090083
			public const int Text1 = 2131296387;
			
			// aapt resource value: 0x7f090084
			public const int Text2 = 2131296388;
			
			// aapt resource value: 0x7f090085
			public const int Text3 = 2131296389;
			
			// aapt resource value: 0x7f09003f
			public const int _imageView = 2131296319;
			
			// aapt resource value: 0x7f090041
			public const int anomalie = 2131296321;
			
			// aapt resource value: 0x7f090069
			public const int authen = 2131296361;
			
			// aapt resource value: 0x7f09006f
			public const int bdgLiv = 2131296367;
			
			// aapt resource value: 0x7f090074
			public const int bdgRam = 2131296372;
			
			// aapt resource value: 0x7f09005e
			public const int btnLivraison = 2131296350;
			
			// aapt resource value: 0x7f09009b
			public const int btnLoad = 2131296411;
			
			// aapt resource value: 0x7f09009a
			public const int btnSave = 2131296410;
			
			// aapt resource value: 0x7f09005c
			public const int btnsearch = 2131296348;
			
			// aapt resource value: 0x7f09002e
			public const int btnsend = 2131296302;
			
			// aapt resource value: 0x7f09007f
			public const int button1 = 2131296383;
			
			// aapt resource value: 0x7f090080
			public const int button2 = 2131296384;
			
			// aapt resource value: 0x7f09000a
			public const int buttonpass = 2131296266;
			
			// aapt resource value: 0x7f090088
			public const int chDateAsc = 2131296392;
			
			// aapt resource value: 0x7f09008a
			public const int chDateDesc = 2131296394;
			
			// aapt resource value: 0x7f09008d
			public const int chStateAsc = 2131296397;
			
			// aapt resource value: 0x7f090090
			public const int chStateDesc = 2131296400;
			
			// aapt resource value: 0x7f090030
			public const int checkBox1 = 2131296304;
			
			// aapt resource value: 0x7f090086
			public const int checkbox = 2131296390;
			
			// aapt resource value: 0x7f09003d
			public const int client = 2131296317;
			
			// aapt resource value: 0x7f090068
			public const int codebarre = 2131296360;
			
			// aapt resource value: 0x7f090039
			public const int codelivraison = 2131296313;
			
			// aapt resource value: 0x7f09006c
			public const int columnlayout1_1 = 2131296364;
			
			// aapt resource value: 0x7f090071
			public const int columnlayout1_2 = 2131296369;
			
			// aapt resource value: 0x7f090076
			public const int columnlayout2_1 = 2131296374;
			
			// aapt resource value: 0x7f09007c
			public const int columnlayout4_2 = 2131296380;
			
			// aapt resource value: 0x7f090038
			public const int commande = 2131296312;
			
			// aapt resource value: 0x7f09009e
			public const int contentFrame = 2131296414;
			
			// aapt resource value: 0x7f09006e
			public const int deliveryBadge = 2131296366;
			
			// aapt resource value: 0x7f090070
			public const int deliveryBadgeText = 2131296368;
			
			// aapt resource value: 0x7f090095
			public const int editText1 = 2131296405;
			
			// aapt resource value: 0x7f090016
			public const int editTextBarcode = 2131296278;
			
			// aapt resource value: 0x7f090043
			public const int editTextCompany = 2131296323;
			
			// aapt resource value: 0x7f090026
			public const int editTextDriving = 2131296294;
			
			// aapt resource value: 0x7f09004d
			public const int editTextGPS = 2131296333;
			
			// aapt resource value: 0x7f090049
			public const int editTextInbox = 2131296329;
			
			// aapt resource value: 0x7f09004b
			public const int editTextOutbox = 2131296331;
			
			// aapt resource value: 0x7f090045
			public const int editTextPhone = 2131296325;
			
			// aapt resource value: 0x7f09001e
			public const int editTextTXPassword = 2131296286;
			
			// aapt resource value: 0x7f090021
			public const int editTextTXSystemNr = 2131296289;
			
			// aapt resource value: 0x7f090047
			public const int editTextTimeout = 2131296327;
			
			// aapt resource value: 0x7f09001b
			public const int editTextTruckID = 2131296283;
			
			// aapt resource value: 0x7f090013
			public const int editTextUserName = 2131296275;
			
			// aapt resource value: 0x7f090029
			public const int editTextWaiting = 2131296297;
			
			// aapt resource value: 0x7f09002d
			public const int editnewmsg = 2131296301;
			
			// aapt resource value: 0x7f09002a
			public const int editrecherche = 2131296298;
			
			// aapt resource value: 0x7f090003
			public const int edittext = 2131296259;
			
			// aapt resource value: 0x7f090065
			public const int edittextlogin = 2131296357;
			
			// aapt resource value: 0x7f090067
			public const int edittextpsw = 2131296359;
			
			// aapt resource value: 0x7f090054
			public const int grp1 = 2131296340;
			
			// aapt resource value: 0x7f090055
			public const int grp2 = 2131296341;
			
			// aapt resource value: 0x7f090056
			public const int grp3 = 2131296342;
			
			// aapt resource value: 0x7f090057
			public const int grp4 = 2131296343;
			
			// aapt resource value: 0x7f090058
			public const int grp5 = 2131296344;
			
			// aapt resource value: 0x7f09000c
			public const int imageButton1 = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int imageButton2 = 2131296270;
			
			// aapt resource value: 0x7f090004
			public const int imageView1 = 2131296260;
			
			// aapt resource value: 0x7f09007a
			public const int imageView2 = 2131296378;
			
			// aapt resource value: 0x7f09006b
			public const int imageView25 = 2131296363;
			
			// aapt resource value: 0x7f090072
			public const int imageView27 = 2131296370;
			
			// aapt resource value: 0x7f09006d
			public const int imageView28 = 2131296365;
			
			// aapt resource value: 0x7f090077
			public const int imageView3 = 2131296375;
			
			// aapt resource value: 0x7f090008
			public const int imgcon = 2131296264;
			
			// aapt resource value: 0x7f09003e
			public const int infoclient = 2131296318;
			
			// aapt resource value: 0x7f09003b
			public const int infolivraison = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int infosupp = 2131296316;
			
			// aapt resource value: 0x7f090000
			public const int layoutanomalie = 2131296256;
			
			// aapt resource value: 0x7f09002b
			public const int layoutlistlivraison = 2131296299;
			
			// aapt resource value: 0x7f09005d
			public const int layoutlisttraitee = 2131296349;
			
			// aapt resource value: 0x7f090078
			public const int lblButton3 = 2131296376;
			
			// aapt resource value: 0x7f09007d
			public const int lblButton8 = 2131296381;
			
			// aapt resource value: 0x7f090087
			public const int lblDateAsc = 2131296391;
			
			// aapt resource value: 0x7f090089
			public const int lblDateDesc = 2131296393;
			
			// aapt resource value: 0x7f09008c
			public const int lblStateAsc = 2131296396;
			
			// aapt resource value: 0x7f09008f
			public const int lblStateDesc = 2131296399;
			
			// aapt resource value: 0x7f09000d
			public const int lblTitle = 2131296269;
			
			// aapt resource value: 0x7f090001
			public const int linearLayout1 = 2131296257;
			
			// aapt resource value: 0x7f09000b
			public const int linearLayout2 = 2131296267;
			
			// aapt resource value: 0x7f09007e
			public const int linearLayout3 = 2131296382;
			
			// aapt resource value: 0x7f09008b
			public const int linearLayout4 = 2131296395;
			
			// aapt resource value: 0x7f09008e
			public const int linearLayout5 = 2131296398;
			
			// aapt resource value: 0x7f090091
			public const int linearLayout6 = 2131296401;
			
			// aapt resource value: 0x7f090092
			public const int linearLayout7 = 2131296402;
			
			// aapt resource value: 0x7f09005a
			public const int listView1 = 2131296346;
			
			// aapt resource value: 0x7f09002c
			public const int listViewBox = 2131296300;
			
			// aapt resource value: 0x7f090062
			public const int loadingImage = 2131296354;
			
			// aapt resource value: 0x7f090060
			public const int loadingProgressBar = 2131296352;
			
			// aapt resource value: 0x7f090063
			public const int loadingProgressWheel = 2131296355;
			
			// aapt resource value: 0x7f09006a
			public const int mainLayout = 2131296362;
			
			// aapt resource value: 0x7f090079
			public const int newMsgBadge = 2131296377;
			
			// aapt resource value: 0x7f09007b
			public const int newMsgBadgeText = 2131296379;
			
			// aapt resource value: 0x7f090005
			public const int openCamera = 2131296261;
			
			// aapt resource value: 0x7f090093
			public const int pass = 2131296403;
			
			// aapt resource value: 0x7f090073
			public const int peekupBadge = 2131296371;
			
			// aapt resource value: 0x7f090075
			public const int peekupBadgeText = 2131296373;
			
			// aapt resource value: 0x7f09009c
			public const int progressBar1 = 2131296412;
			
			// aapt resource value: 0x7f090035
			public const int radioButton1 = 2131296309;
			
			// aapt resource value: 0x7f090034
			public const int radioButton2 = 2131296308;
			
			// aapt resource value: 0x7f090033
			public const int radioGroup1 = 2131296307;
			
			// aapt resource value: 0x7f09002f
			public const int relativeLayout1 = 2131296303;
			
			// aapt resource value: 0x7f090032
			public const int relativeLayout2 = 2131296306;
			
			// aapt resource value: 0x7f090098
			public const int rootView = 2131296408;
			
			// aapt resource value: 0x7f09000f
			public const int rowLayout1 = 2131296271;
			
			// aapt resource value: 0x7f090022
			public const int rowLayout10 = 2131296290;
			
			// aapt resource value: 0x7f090024
			public const int rowLayout11 = 2131296292;
			
			// aapt resource value: 0x7f090027
			public const int rowLayout12 = 2131296295;
			
			// aapt resource value: 0x7f090011
			public const int rowLayout2 = 2131296273;
			
			// aapt resource value: 0x7f090014
			public const int rowLayout3 = 2131296276;
			
			// aapt resource value: 0x7f090017
			public const int rowLayout4 = 2131296279;
			
			// aapt resource value: 0x7f090019
			public const int rowLayout5 = 2131296281;
			
			// aapt resource value: 0x7f09001c
			public const int rowLayout6 = 2131296284;
			
			// aapt resource value: 0x7f09001f
			public const int rowLayout7 = 2131296287;
			
			// aapt resource value: 0x7f090050
			public const int rowLayout8 = 2131296336;
			
			// aapt resource value: 0x7f090036
			public const int scrollView1 = 2131296310;
			
			// aapt resource value: 0x7f090099
			public const int signatureView = 2131296409;
			
			// aapt resource value: 0x7f090002
			public const int spinnerAnomalie = 2131296258;
			
			// aapt resource value: 0x7f09004f
			public const int spinnerConnection = 2131296335;
			
			// aapt resource value: 0x7f090052
			public const int spinnerLanguage = 2131296338;
			
			// aapt resource value: 0x7f090007
			public const int strut = 2131296263;
			
			// aapt resource value: 0x7f090037
			public const int tableLayout1 = 2131296311;
			
			// aapt resource value: 0x7f090096
			public const int tableRow1 = 2131296406;
			
			// aapt resource value: 0x7f090064
			public const int textView1 = 2131296356;
			
			// aapt resource value: 0x7f090066
			public const int textView2 = 2131296358;
			
			// aapt resource value: 0x7f090015
			public const int textViewBarcode = 2131296277;
			
			// aapt resource value: 0x7f090042
			public const int textViewCompany = 2131296322;
			
			// aapt resource value: 0x7f09004e
			public const int textViewConnection = 2131296334;
			
			// aapt resource value: 0x7f090025
			public const int textViewDriving = 2131296293;
			
			// aapt resource value: 0x7f09004c
			public const int textViewGPS = 2131296332;
			
			// aapt resource value: 0x7f090059
			public const int textViewGrp = 2131296345;
			
			// aapt resource value: 0x7f090010
			public const int textViewHeader1 = 2131296272;
			
			// aapt resource value: 0x7f090023
			public const int textViewHeader10 = 2131296291;
			
			// aapt resource value: 0x7f090018
			public const int textViewHeader2 = 2131296280;
			
			// aapt resource value: 0x7f090048
			public const int textViewInbox = 2131296328;
			
			// aapt resource value: 0x7f090051
			public const int textViewLanguage = 2131296337;
			
			// aapt resource value: 0x7f09004a
			public const int textViewOutbox = 2131296330;
			
			// aapt resource value: 0x7f090044
			public const int textViewPhone = 2131296324;
			
			// aapt resource value: 0x7f090061
			public const int textViewStatus = 2131296353;
			
			// aapt resource value: 0x7f09001d
			public const int textViewTXPassword = 2131296285;
			
			// aapt resource value: 0x7f090020
			public const int textViewTXSystemNr = 2131296288;
			
			// aapt resource value: 0x7f090046
			public const int textViewTimeout = 2131296326;
			
			// aapt resource value: 0x7f09001a
			public const int textViewTruckID = 2131296282;
			
			// aapt resource value: 0x7f090012
			public const int textViewUserName = 2131296274;
			
			// aapt resource value: 0x7f090028
			public const int textViewWaiting = 2131296296;
			
			// aapt resource value: 0x7f090031
			public const int textcr = 2131296305;
			
			// aapt resource value: 0x7f090097
			public const int textds = 2131296407;
			
			// aapt resource value: 0x7f09003a
			public const int title = 2131296314;
			
			// aapt resource value: 0x7f090053
			public const int toutgrp = 2131296339;
			
			// aapt resource value: 0x7f09005b
			public const int traitees = 2131296347;
			
			// aapt resource value: 0x7f09005f
			public const int txtName = 2131296351;
			
			// aapt resource value: 0x7f090009
			public const int txttable = 2131296265;
			
			// aapt resource value: 0x7f090040
			public const int valide = 2131296320;
			
			// aapt resource value: 0x7f090006
			public const int valideAnomalie = 2131296262;
			
			// aapt resource value: 0x7f090094
			public const int validpass = 2131296404;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Anomalie = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Auth = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AuthConfig = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int btncodebarre = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ChatLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int checkbox = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DetailLivraison = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int GeneralConfig = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListeEnlevement = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ListeLivraison = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListeLivraisonMultiGrp = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ListeTraitee = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ListeTraiteeEnlevement = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ListeViewDelete = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ListeViewRow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int ListeViewRowADR = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ListeViewRowAnomalie = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ListeViewRowAnomaliePJ = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ListeViewRowRamasse = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ListeViewRowStroke = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int ListeViewRowValide = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int loading = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int loadingimage = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int loadingprogress = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int login = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int LoginChoose = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Main = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int MessageList = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int MessageListDelete = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int MessageListDeleteItem = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int MessageListItem = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int MessageListSorting = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Modal = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int NewMessage = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int RowLeft = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int RowRight = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int Signature = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int Splashscreen = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int SujList = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int Webservice = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int zxingscanneractivitylayout = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int zxingscannerfragmentlayout = 2130903081;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep2 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int beep4 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int msg = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int msg2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int msg3 = 2130968580;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int button_text = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
